"""Bilibili video subtitle extractor."""

import logging
import re

from bilibili_api import video, Credential

from app.tools.extractors.base import (
    ContentExtractor,
    ExtractionError,
    ExtractionResult,
    RawContentChunk,
)
from app.tools.extractors.utils import group_segments

logger = logging.getLogger(__name__)


class BilibiliExtractor(ContentExtractor):
    """Extract subtitles from Bilibili videos.

    Subtitle priority:
    1. CC subtitles (human-uploaded, highest quality)
    2. AI-generated subtitles (auto-generated by Bilibili)
    3. No subtitles → Whisper ASR fallback

    Cookie auth is optional but recommended — some videos restrict
    subtitle access to logged-in users.
    """

    def __init__(
        self,
        credential: Credential | None = None,
        whisper_mode: str = "api",
        whisper_model: str = "base",
        whisper_api_key: str = "",
        whisper_api_base_url: str = "https://api.groq.com/openai/v1",
        whisper_api_model: str = "whisper-large-v3",
    ):
        """Initialize with optional Bilibili credential.

        Args:
            credential: bilibili_api.Credential for authenticated access.
                Created from SESSDATA + bili_jct + buvid3 cookies.
                If None, only publicly accessible subtitles work.
            whisper_mode: Whisper ASR mode ("api" or "local").
            whisper_model: Whisper model name for local mode.
        """
        self.credential = credential
        self._whisper_mode = whisper_mode
        self._whisper_model = whisper_model
        self._whisper_api_key = whisper_api_key
        self._whisper_api_base_url = whisper_api_base_url
        self._whisper_api_model = whisper_api_model

    def supported_source_type(self) -> str:
        return "bilibili"

    async def extract(self, source: str, **kwargs) -> ExtractionResult:
        """Extract subtitles from a Bilibili video URL.

        Supports both single-page videos and multi-page playlists (合集).
        If the video has multiple pages and no specific ``page`` kwarg is
        passed, ALL pages are extracted and their chunks are merged into a
        single ExtractionResult.

        Args:
            source: Bilibili URL (e.g. "https://www.bilibili.com/video/BV1xx...")
            **kwargs:
                page: int — for multi-part videos, extract only that part (0-indexed).
                    If omitted and the video has >1 pages, all pages are extracted.

        Returns:
            ExtractionResult with subtitle chunks (tagged with page metadata for
            playlists).
        """
        bvid = self._parse_bvid(source)
        page_kwarg = kwargs.get("page")  # None means "not specified"

        v = video.Video(bvid=bvid, credential=self.credential)

        # 1. Get video info (title, duration, pages)
        info = await v.get_info()
        title = info["title"]
        duration = info.get("duration", 0)
        pages = info.get("pages", [])

        is_playlist = len(pages) > 1

        # Decide which pages to process
        if page_kwarg is not None:
            # Caller explicitly requested a single page
            page_index = int(page_kwarg)
            if page_index >= len(pages) and len(pages) > 0:
                raise ExtractionError(
                    f"Page {page_index} not found. Video has {len(pages)} pages.",
                    source_type="bilibili",
                    details={"bvid": bvid, "page_count": len(pages)},
                )
            pages_to_process = [(page_index, pages[page_index])] if pages else [(0, None)]
        elif is_playlist:
            # Multi-page video — process all pages
            pages_to_process = list(enumerate(pages))
        else:
            # Single-page video
            pages_to_process = [(0, pages[0])] if pages else [(0, None)]

        all_chunks: list[RawContentChunk] = []
        subtitle_sources: list[str] = []

        for page_index, page_info in pages_to_process:
            cid = page_info["cid"] if page_info else info.get("cid")
            page_title = page_info.get("part", "") if page_info else title

            chunks, subtitle_source = await self._extract_single_page(
                v=v,
                bvid=bvid,
                cid=cid,
                page_index=page_index,
                page_title=page_title,
                source=source,
                tag_page=is_playlist,
                is_multi_page=is_playlist,
            )
            all_chunks.extend(chunks)
            subtitle_sources.append(subtitle_source)

        # Summarise subtitle sources (deduplicated, comma-joined)
        seen: list[str] = []
        for s in subtitle_sources:
            if s not in seen:
                seen.append(s)
        combined_source = ", ".join(seen)

        base_metadata: dict = {
            "platform": "bilibili",
            "video_id": bvid,
            "bvid": bvid,
            "title": title,
            "author": info.get("owner", {}).get("name", ""),
            "duration": duration,
            "subtitle_source": combined_source,
            "media_url": f"https://www.bilibili.com/video/{bvid}",
            "is_playlist": is_playlist,
            "page_count": len(pages),
            "pages": [
                {"index": i, "title": p.get("part", ""), "cid": p["cid"]}
                for i, p in enumerate(pages)
            ],
        }

        # For single-page requests keep legacy ``page`` + ``cid`` keys
        if page_kwarg is not None or not is_playlist:
            resolved_page = int(page_kwarg) if page_kwarg is not None else 0
            cid = pages[resolved_page]["cid"] if pages else info.get("cid")
            base_metadata["page"] = resolved_page
            base_metadata["cid"] = cid

        return ExtractionResult(
            title=title,
            chunks=all_chunks,
            metadata=base_metadata,
        )

    async def _extract_single_page(
        self,
        v: "video.Video",
        bvid: str,
        cid: int,
        page_index: int,
        page_title: str,
        source: str,
        tag_page: bool = False,
        is_multi_page: bool = False,
    ) -> tuple[list[RawContentChunk], str]:
        """Extract subtitles for a single page/part of a video.

        Args:
            v: bilibili_api Video object.
            bvid: BV number string.
            cid: Page CID.
            page_index: 0-based index of this page.
            page_title: Human-readable title from ``page["part"]``.
            source: Original source URL (used for Whisper fallback).
            tag_page: If True, add ``page_index`` and ``page_title`` to each
                chunk's metadata (used for playlist extraction).
            is_multi_page: If True, append ``?p=<n>`` to the media URL.

        Returns:
            Tuple of (chunks, subtitle_source_string).
        """
        media_url = f"https://www.bilibili.com/video/{bvid}"
        if is_multi_page:
            media_url = f"{media_url}?p={page_index + 1}"

        subtitle_info = await v.get_subtitle(cid=cid)
        subtitles = subtitle_info.get("subtitles", [])

        if not subtitles:
            logger.info(
                f"No subtitles for {bvid} page {page_index}, falling back to Whisper ASR"
            )
            from app.tools.extractors.asr import WhisperService
            whisper = WhisperService(
                mode=self._whisper_mode,
                model=self._whisper_model,
                api_key=self._whisper_api_key,
                api_base_url=self._whisper_api_base_url,
                api_model=self._whisper_api_model,
            )
            try:
                segments = await whisper.transcribe(source)
            except Exception as exc:
                raise ExtractionError(
                    "B站视频没有可用字幕，系统尝试下载音频用于语音转写，但音频下载失败。"
                    "这通常是当前网络无法稳定访问 B站视频 CDN，或容器代理未生效。"
                    "请稍后重试、切换网络/代理，或换一个带字幕的视频。",
                    source_type="bilibili",
                    details={
                        "bvid": bvid,
                        "cid": cid,
                        "page_index": page_index,
                        "fallback": "whisper",
                        "cause": str(exc),
                    },
                ) from exc
            subtitle_source = "whisper"
            chunks = group_segments(
                segments=segments, source_type="bilibili",
                media_url=media_url, window_seconds=60,
            )
        else:
            best_subtitle = self._pick_best_subtitle(subtitles)

            subtitle_url = best_subtitle["subtitle_url"]
            if subtitle_url.startswith("//"):
                subtitle_url = "https:" + subtitle_url

            import httpx
            async with httpx.AsyncClient() as client:
                resp = await client.get(subtitle_url)
                resp.raise_for_status()
                subtitle_data = resp.json()

            subtitle_source = best_subtitle.get("lan", "unknown")
            chunks = group_segments(
                segments=subtitle_data.get("body", []),
                source_type="bilibili",
                media_url=media_url, window_seconds=60,
            )

        if tag_page:
            for chunk in chunks:
                chunk.metadata["page_index"] = page_index
                chunk.metadata["page_title"] = page_title

        return chunks, subtitle_source

    @staticmethod
    def _parse_bvid(url: str) -> str:
        """Extract BV号 from various Bilibili URL formats.

        Supports:
        - https://www.bilibili.com/video/BV1xx411c7XW
        - https://b23.tv/BV1xx411c7XW
        - https://www.bilibili.com/video/BV1xx411c7XW?p=2
        - BV1xx411c7XW (raw BV号)
        """
        # Direct BV号
        if re.match(r"^BV[\w]+$", url):
            return url

        # URL patterns
        match = re.search(r"(BV[\w]+)", url)
        if match:
            return match.group(1)

        raise ExtractionError(
            f"Cannot parse BV号 from URL: {url}",
            source_type="bilibili",
            details={"url": url},
        )

    @staticmethod
    def _pick_best_subtitle(subtitles: list[dict]) -> dict:
        """Pick the best subtitle track.

        Priority: CC zh-CN > CC zh > AI zh > any CC > any AI > first available
        """
        cc_subs = [s for s in subtitles if not s.get("lan", "").startswith("ai-")]
        ai_subs = [s for s in subtitles if s.get("lan", "").startswith("ai-")]

        # Prefer Chinese CC
        for sub in cc_subs:
            if sub.get("lan") in ("zh-CN", "zh-Hans"):
                return sub
        for sub in cc_subs:
            if "zh" in sub.get("lan", ""):
                return sub

        # Then Chinese AI
        for sub in ai_subs:
            if "zh" in sub.get("lan", ""):
                return sub

        # Fallback
        return cc_subs[0] if cc_subs else ai_subs[0] if ai_subs else subtitles[0]
