"""add goal to courses

Revision ID: 0c5bd93240f4
Revises: da1c8232ec8f
Create Date: 2026-03-28 15:39:59.108054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5bd93240f4'
down_revision: Union[str, Sequence[str], None] = 'da1c8232ec8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('goal', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'goal')
    # ### end Alembic commands ###
