"""add whisper_configs table

Revision ID: 258d5c930d9c
Revises: bb06294270e4
Create Date: 2026-03-28 18:18:22.701532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258d5c930d9c'
down_revision: Union[str, Sequence[str], None] = 'bb06294270e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whisper_configs',
    sa.Column('mode', sa.String(length=20), server_default=sa.text("'api'"), nullable=False),
    sa.Column('api_base_url', sa.String(length=500), nullable=True),
    sa.Column('api_model', sa.String(length=100), nullable=True),
    sa.Column('api_key_encrypted', sa.String(), nullable=True),
    sa.Column('local_model', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whisper_configs')
    # ### end Alembic commands ###
