"""add_model_config_tables

Revision ID: 3b36dc85a8ce
Revises: e0c15b1a7a23
Create Date: 2026-03-24 20:59:08.814267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b36dc85a8ce'
down_revision: Union[str, Sequence[str], None] = 'e0c15b1a7a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('api_key_encrypted', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('supports_tool_use', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('supports_streaming', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('max_tokens_limit', sa.Integer(), server_default=sa.text('4096'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_name'), 'model_configs', ['name'], unique=True)
    op.create_table('model_route_configs',
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_name'], ['model_configs.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_route_configs')
    op.drop_index(op.f('ix_model_configs_name'), table_name='model_configs')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
