"""add labs table

Revision ID: 6d8cec3bdd57
Revises: ea9b021a2471
Create Date: 2026-03-25 22:43:09.274820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d8cec3bdd57'
down_revision: Union[str, Sequence[str], None] = 'ea9b021a2471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodic_embedding'), table_name='episodic_memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('labs', sa.Column('language', sa.String(length=50), nullable=False))
    op.add_column('labs', sa.Column('test_code', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('labs', sa.Column('solution_code', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('labs', sa.Column('run_instructions', sa.Text(), nullable=False))
    op.add_column('labs', sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False))
    op.alter_column('labs', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    # Cast TEXT → JSONB requires explicit USING clause
    op.execute("ALTER TABLE labs ALTER COLUMN starter_code TYPE JSONB USING starter_code::jsonb")
    op.create_index(op.f('ix_labs_section_id'), 'labs', ['section_id'], unique=False)
    op.drop_column('labs', 'test_cases')
    op.drop_column('labs', 'hints')
    op.drop_column('labs', 'solution')
    op.drop_column('labs', 'estimated_minutes')
    op.drop_column('labs', 'difficulty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('labs', sa.Column('estimated_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('labs', sa.Column('solution', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('labs', sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('labs', sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_labs_section_id'), table_name='labs')
    op.alter_column('labs', 'starter_code',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('labs', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('labs', 'confidence')
    op.drop_column('labs', 'run_instructions')
    op.drop_column('labs', 'solution_code')
    op.drop_column('labs', 'test_code')
    op.drop_column('labs', 'language')
    op.create_index(op.f('ix_episodic_embedding'), 'episodic_memories', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
