"""add model_type to model_configs

Revision ID: 7b674642962a
Revises: 0c5bd93240f4
Create Date: 2026-03-28 16:14:40.506454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b674642962a'
down_revision: Union[str, Sequence[str], None] = '0c5bd93240f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_configs', sa.Column('model_type', sa.String(length=20), server_default=sa.text("'chat'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_configs', 'model_type')
    # ### end Alembic commands ###
