"""add section_progress table

Revision ID: 8650c9317bb1
Revises: 6d8cec3bdd57
Create Date: 2026-03-30 22:45:07.918193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8650c9317bb1'
down_revision: Union[str, Sequence[str], None] = '6d8cec3bdd57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('lab_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('exercise_best_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'section_id', name='uq_progress_user_section')
    )
    op.create_index(op.f('ix_section_progress_section_id'), 'section_progress', ['section_id'], unique=False)
    op.create_index(op.f('ix_section_progress_user_id'), 'section_progress', ['user_id'], unique=False)
    op.alter_column('labs', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('labs', 'starter_code',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labs', 'starter_code',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('labs', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_section_progress_user_id'), table_name='section_progress')
    op.drop_index(op.f('ix_section_progress_section_id'), table_name='section_progress')
    op.drop_table('section_progress')
    # ### end Alembic commands ###
