"""add exercise_submissions and review_items tables

Revision ID: 9b1fe9176918
Revises: da582a2a475e
Create Date: 2026-03-25 14:30:55.794640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1fe9176918'
down_revision: Union[str, Sequence[str], None] = 'da582a2a475e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_submissions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_submissions_exercise_id'), 'exercise_submissions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_submissions_user_id'), 'exercise_submissions', ['user_id'], unique=False)
    op.create_table('review_items',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=True),
    sa.Column('easiness', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('review_at', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_review_user_concept')
    )
    op.create_index('ix_review_user_due', 'review_items', ['user_id', 'review_at'], unique=False)
    op.drop_index(op.f('ix_users_oauth_provider_id'), table_name='users', postgresql_where='(oauth_provider IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_oauth_provider_id'), 'users', ['oauth_provider', 'oauth_id'], unique=True, postgresql_where='(oauth_provider IS NOT NULL)')
    op.drop_index('ix_review_user_due', table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_exercise_submissions_user_id'), table_name='exercise_submissions')
    op.drop_index(op.f('ix_exercise_submissions_exercise_id'), table_name='exercise_submissions')
    op.drop_table('exercise_submissions')
    # ### end Alembic commands ###
