"""add bilibili_credentials table

Revision ID: c46e39d7e515
Revises: 258d5c930d9c
Create Date: 2026-03-28 21:18:59.365774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46e39d7e515'
down_revision: Union[str, Sequence[str], None] = '258d5c930d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bilibili_credentials',
    sa.Column('sessdata_encrypted', sa.Text(), nullable=True),
    sa.Column('bili_jct_encrypted', sa.Text(), nullable=True),
    sa.Column('dedeuserid', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bilibili_credentials')
    # ### end Alembic commands ###
