"""add content_key and ref_source_id to sources

Revision ID: da1c8232ec8f
Revises: 220861084881
Create Date: 2026-03-28 14:46:36.706412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1c8232ec8f'
down_revision: Union[str, Sequence[str], None] = '220861084881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('content_key', sa.String(length=255), nullable=True))
    op.add_column('sources', sa.Column('ref_source_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_sources_content_key'), 'sources', ['content_key'], unique=False)
    op.create_foreign_key(None, 'sources', 'sources', ['ref_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_index(op.f('ix_sources_content_key'), table_name='sources')
    op.drop_column('sources', 'ref_source_id')
    op.drop_column('sources', 'content_key')
    # ### end Alembic commands ###
