"""add auth fields, multi-tenant models, usage logs

Revision ID: da582a2a475e
Revises: 3b36dc85a8ce
Create Date: 2026-03-25 13:41:10.014676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da582a2a475e'
down_revision: Union[str, Sequence[str], None] = '3b36dc85a8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_user_date', 'llm_usage_logs', ['user_id', 'created_at'], unique=False)
    op.add_column('model_configs', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_model_configs_user_id'), 'model_configs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'model_configs', 'users', ['user_id'], ['id'])
    op.add_column('model_route_configs', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_model_route_configs_user_id'), 'model_route_configs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'model_route_configs', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(
        'ix_users_oauth_provider_id',
        'users',
        ['oauth_provider', 'oauth_id'],
        unique=True,
        postgresql_where=sa.text('oauth_provider IS NOT NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_oauth_provider_id', table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    op.drop_constraint(None, 'model_route_configs', type_='foreignkey')
    op.drop_index(op.f('ix_model_route_configs_user_id'), table_name='model_route_configs')
    op.drop_column('model_route_configs', 'user_id')
    op.drop_constraint(None, 'model_configs', type_='foreignkey')
    op.drop_index(op.f('ix_model_configs_user_id'), table_name='model_configs')
    op.drop_column('model_configs', 'user_id')
    op.drop_index('ix_usage_user_date', table_name='llm_usage_logs')
    op.drop_table('llm_usage_logs')
    # ### end Alembic commands ###
