"""add episodic_memories, metacognitive_records, translations

Revision ID: ea9b021a2471
Revises: 9b1fe9176918
Create Date: 2026-03-25 14:44:24.122096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ea9b021a2471'
down_revision: Union[str, Sequence[str], None] = '9b1fe9176918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodic_memories',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('importance', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_episodic_expires', 'episodic_memories', ['expires_at'], unique=False, postgresql_where='expires_at IS NOT NULL')
    op.create_index('ix_episodic_user_importance', 'episodic_memories', ['user_id', 'importance'], unique=False)
    op.execute("CREATE INDEX IF NOT EXISTS ix_episodic_embedding ON episodic_memories USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)")
    op.create_table('metacognitive_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('effectiveness', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metacog_user_eff', 'metacognitive_records', ['user_id', 'effectiveness'], unique=False)
    op.create_table('translations',
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['content_chunks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'target_lang', name='uq_translation_chunk_lang')
    )
    op.create_index(op.f('ix_translations_chunk_id'), 'translations', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_chunk_id'), table_name='translations')
    op.drop_table('translations')
    op.drop_index('ix_metacog_user_eff', table_name='metacognitive_records')
    op.drop_table('metacognitive_records')
    op.drop_index('ix_episodic_user_importance', table_name='episodic_memories')
    op.drop_index('ix_episodic_expires', table_name='episodic_memories', postgresql_where='expires_at IS NOT NULL')
    op.execute("DROP INDEX IF EXISTS ix_episodic_embedding")
    op.drop_table('episodic_memories')
    # ### end Alembic commands ###
