"""add duration_ms to llm_usage_logs

Revision ID: edd715700988
Revises: 942f0ec50aae
Create Date: 2026-03-28 13:45:41.296703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edd715700988'
down_revision: Union[str, Sequence[str], None] = '942f0ec50aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labs', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('labs', 'starter_code',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.add_column('llm_usage_logs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_usage_logs', 'duration_ms')
    op.alter_column('labs', 'starter_code',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('labs', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
